version: '3.8'

services:
  wog_flask:
    image: wog_world:01
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8777:5000"
    volumes:
      - "/c/jenkins/volumes/scoresmount.txt:/app/datafiles/score.txt"
