version: '3.8'

services:
  wog_flask:
    image: ${DOCKER_IMAGE_PREFIX}wog_world:${IMAGE_VERSION}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8777:5000"
    volumes:
      - "/c/jenkins/volumes/wog_data:/app/datafiles"
    container_name: wog_flask
