version: '3.8'

services:
  flask-app:
    image: wog_world:01
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8777:5000"
    volumes:
      - "./score_mount.txt:/app/datafiles/score.txt"
